### ISSUE TITLE
Alignment for dropdown

### ISSUE THREAD

**Issue by BasselArt** [pishran/nova-rtl-theme#3]
Thanks for the great theme, I have a small issue and can't fix it, some dropdown not viewed correctly,
attached a screenshot to describe the issue.
I have a custom CSS file but I need some tips to fixe this.

Regards.

![Screen Shot 2019-11-03 at 8 25 10 AM](https://user-images.githubusercontent.com/5476744/68080815-f9c85400-fe13-11e9-918c-a78c266a80a1.png)
![Screen Shot 2019-11-03 at 8 25 16 AM](https://user-images.githubusercontent.com/5476744/68080816-f9c85400-fe13-11e9-8c42-1c842e285c5a.png)
![Screen Shot 2019-11-03 at 8 24 55 AM](https://user-images.githubusercontent.com/5476744/68080817-fa60ea80-fe13-11e9-9a92-bbfbc79f74a1.png)

**Comment by FaridAghili** [comment]
Yes, already noticed that, didn't find a fix though.
Feel free to make a PR.

**Comment by sepehrr** [comment]
this problem is because of `popper.js`.
do this to solve the problem (assuming nova resides in `/nova/`):
1. change 'bottom-end' to 'bottom-start' in `/nova/resource/js/components/Dropdown.vue`
2. change 'bottom-start' to 'bottom-end' in `/nova/resource/js/components/SearchInput.vue`
3. change 'bottom-start' to 'bottom-end' in `/nova/resource/js/views/Index.vue`
5. make a `webpack.mix.js` file in your nova folder. (duplicate `/nova/webpack.mix.js.dist` to `/nova/webpack.mix.js` is just ok)
6. `cd nova`
6. run `npm install`
7. run `npm run prod`
8. now in laravel folder run `php artisan nova:publish`

now your Nova is RTL-friendly!

**Comment by FaridAghili** [comment]
@sepehrr 
Thank you for explanation, it works but can't be used cause we need a way to implement it in our package.
Editing Nova's source is not an option.

**Comment by SadeghPM** [comment]
> Yes, already noticed that, didn't find a fix though.
> Feel free to make a PR.

this fix issue in any screen size:
```css
div.tooltip[x-placement="top-start"],div.tooltip[x-placement="bottom-start"]{
    left: 220px !important;
}
div.tooltip[x-placement="top-end"],div.tooltip[x-placement="bottom-end"]{
    left: -200px !important;
}
```

**Comment by FaridAghili** [comment]
Thanks.

Your code make change from this:
![image](https://user-images.githubusercontent.com/8607021/69911287-77d94400-142e-11ea-9bab-32f65802a9b3.png)

To this:
![image](https://user-images.githubusercontent.com/8607021/69911294-83c50600-142e-11ea-85a9-d4cb137e8baf.png)

While expected result in something like this:
![image](https://user-images.githubusercontent.com/8607021/69911320-c7b80b00-142e-11ea-9e2f-f3c1c91c4237.png)

**Comment by FaridAghili** [comment]
I see that you've fixed filter and selection popups thu
![image](https://user-images.githubusercontent.com/8607021/69911342-5dec3100-142f-11ea-839a-10f567db989a.png)
![image](https://user-images.githubusercontent.com/8607021/69911344-63e21200-142f-11ea-91f0-828bca813cee.png)
Thank you.

Do you have any idea about the user menu?

**Comment by SadeghPM** [comment]
Unfortunately no. 
‌But quick and dirty way is: replace direction `bottom-start` with `bottom-end` in nova `app.js` resource. There is only two place to replace and its pattern like `placement:{type:String,default:"bottom-start"}`.
This work for me in nova 2.8.

![Screenshot from 2019-12-06 10-26-17](https://user-images.githubusercontent.com/9298600/70302677-e9403a80-1812-11ea-9aea-401fef5fe3fa.png)


![Screenshot from 2019-12-06 10-26-00](https://user-images.githubusercontent.com/9298600/70302678-e9403a80-1812-11ea-9554-9f6c12a94480.png)


![Screenshot from 2019-12-06 10-25-36](https://user-images.githubusercontent.com/9298600/70302680-e9d8d100-1812-11ea-94aa-ec83a35842a9.png)

**Comment by FaridAghili** [comment]
@SadeghPM Editing Nova's source code is not an option because after updating Nova to newer version you will lose all your changes.

**Comment by FaridAghili** [comment]
It should be fixed in https://github.com/pishran/nova-rtl-theme/commit/6a01d9031940bc09834969781279b106c5f2b27c with some js magic! Needs a little testing thu.

**Comment by FaridAghili** [comment]
@BasselArt @sepehrr @SadeghPM 
Can you please test https://github.com/pishran/nova-rtl-theme/commit/6a01d9031940bc09834969781279b106c5f2b27c and let me know to result?

**Comment by FaridAghili** [comment]
Fixed in [v1.3.1](https://github.com/pishran/nova-rtl-theme/releases/tag/v1.3.1).

**Comment by SadeghPM** [comment]
some problem in v1.3.1:

![Screenshot from 2019-12-09 15-43-48](https://user-images.githubusercontent.com/9298600/70434976-ec4d5c00-1a9a-11ea-9ddb-5880ade3a8cd.png)

![Screenshot from 2019-12-09 15-39-19](https://user-images.githubusercontent.com/9298600/70434985-f2433d00-1a9a-11ea-898d-10ddf6f70412.png)

![Screenshot from 2019-12-09 15-39-09](https://user-images.githubusercontent.com/9298600/70434992-f707f100-1a9a-11ea-8ff0-a3f0a7d656ae.png)

**Comment by kfirba** [comment]
I've submitted a PR that fixes the alignment of the dropdowns: https://github.com/laravel/nova/pull/793

@FaridAghili

**Comment by abdallah84** [comment]
i upgrade to latest versions of theme, but i still face the problem

![top corner left bug](https://user-images.githubusercontent.com/17456402/74603141-73353b00-50c1-11ea-8ca3-72e3a23c7ecf.PNG)

**Comment by kfirba** [comment]
@abdallah84 The PR on nova's repository was not yet reviewed.

**Comment by amidesfahani** [comment]
use this hack to bring left aligned buttons to right
`
.card .flex.items-center.ml-auto.px-3 {
    margin-right: 0 !important;
}
`

**Comment by FaridAghili** [comment]
@amidesfahani

Thanks, but it goes like this:
![ss](https://user-images.githubusercontent.com/8607021/82821752-df41ef00-9eb9-11ea-9342-dbc5f111207a.jpg)

**Comment by SadeghPM** [comment]
> @amidesfahani
> 
> Thanks, but it goes like this:

Yeh, but better than this:
![ss](https://user-images.githubusercontent.com/17456402/74603141-73353b00-50c1-11ea-8ca3-72e3a23c7ecf.PNG)

**Comment by 3adeling** [comment]
I have issue when using with [laravel-nova-theme-responsive](https://github.com/gregoriohc/laravel-nova-theme-responsive).

in mobile view (RTL only), when clicking on the profile dropdown I get blank page because of the huge transfrom ` transform: translate3d(-3535px, 53px, 0px);`  in the dropdown popup:

```
<div id="popover_iqs6hnofpb" aria-hidden="false" tabindex="0" class="z-50 open" style="visibility: visible; position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-3535px, 53px, 0px);" x-placement="bottom-start"><div class=""><div class="" style="position: relative;"><div><div class="select-none overflow-hidden bg-white border border-60 shadow rounded-lg" direction="ltr" style="width: 200px;">
/** .... ***/
</div></div> <div data-v-b329ee4c="" tabindex="-1" class="resize-observer"><object aria-hidden="true" tabindex="-1" type="text/html" data="about:blank" __idm_frm__="344"></object></div></div> <div class="" style="left: 0px;"></div></div></div>
```

I am not sure what is the cause of the issue

**Comment by FaridAghili** [comment]
@3adeling This is a known issues, we tried several workaround (you can check them out in the comments above) but couldn't fix it.
That `transform` property is calculated by Popper.js based on several things.

Feel free to give it a try.

**Comment by ali-shabani** [comment]
I fixed the problem with this pr https://github.com/pishran/nova-rtl-theme/pull/7

**Comment by FaridAghili** [comment]
Fixed in [v1.5](https://github.com/pishran/nova-rtl-theme/releases/tag/v1.5) thanks to @pyramid-ali.

**Comment by ImanR7** [comment]
@FaridAghili 

The problem is still unresolved after install Nova 3.21.0 and last version of nova-rtl-theme.

![image](https://user-images.githubusercontent.com/22983388/106652978-7748ba00-65ab-11eb-886f-99601b268e33.png)


Also there is some error in my console as you can see.

![image](https://user-images.githubusercontent.com/22983388/106652633-fb4e7200-65aa-11eb-978c-e76924542d21.png)
