### ISSUE TITLE
Few missing RTL edits

### ISSUE THREAD

**Issue by kfirba** [pishran/nova-rtl-theme#6]
Hey,

I've submitted a PR that fixes the Dropdowns alignment. As part of the work to ensure the dropdowns work as expected, I've encountered a few issues:

1. The lenses view has its back arrow in the wrong direction:
![image](https://user-images.githubusercontent.com/8510486/74529659-1f93e780-4f31-11ea-9273-1b840d99fc95.png)

2. The currently authenticated user dropdown  has `left: 112px !important` injected via a custom <style> tag:

```css
<style type="text/css">#popover_04d1sugnm5{left: 112px !important;}</style>
```

![image](https://user-images.githubusercontent.com/8510486/74529808-45b98780-4f31-11ea-8187-637d37d8334c.png)

I could not find which component injects this.  We need to set it to `left: 0` and the dropdown aligns itself just perfectly.

**Comment by FaridAghili** [comment]
@kfirba dropdown alignments issue has been fixed in [v1.5](https://github.com/pishran/nova-rtl-theme/releases/tag/v1.5).

**Comment by bredisvictor** [comment]
Problem is still there
<img width="425" alt="Screen Shot 2020-09-04 at 6 11 36 PM" src="https://user-images.githubusercontent.com/24625107/92255026-6dc30500-eeda-11ea-806b-b3e2663ba254.png">

**Comment by FaridAghili** [comment]
@bredisvictor what's your nova's version?

**Comment by bredisvictor** [comment]
> @bredisvictor what's your nova's version?

3.0

**Comment by FaridAghili** [comment]
> > @bredisvictor what's your nova's version?
> 
> 3.0

Can you update to 3.8.4 and share the result?

Also mentioning @pyramid-ali.

**Comment by bredisvictor** [comment]
> > > @bredisvictor what's your nova's version?
> > 
> > 
> > 3.0
> 
> Can you update to 3.8.4 and share the result?
> 
> Also mentioning @pyramid-ali.

Thanks for the fast answers.
I will try now.

**Comment by bredisvictor** [comment]
Fixed with nova 3.8.4.
Thanks!

**Comment by FaridAghili** [comment]
@bredisvictor Thank you.

**Comment by FaridAghili** [comment]
@kfirba both issue about dropdown alignment and lens back arrow been fixed in v1.5 and v1.5.1.
please update to latest version of nova and nova-rtl-theme.
